DelightGenie/Models/DbModels/NotificationModels/Notification.cs
using System;
using DelightGenie.Models.DbModels.AccountModels;

namespace DelightGenie.Models.DbModels.NotificationModels
{
    public abstract class Notification : AbstractModel
    {
        public DateTime? NotificationDate { get; set; }

        public virtual Employee Employee { get; set; }
    }
}

DelightGenie/Controllers/NotificationsController.cs
using System;
using System.Web.Mvc;
using DelightGenie.DAL;
using DelightGenie.Models.DbModels.AccountModels;
using DelightGenie.Models.ViewModels.AdminVM;
using DelightGenie.Special;

namespace DelightGenie.Controllers
{
    public class NotificationsController : Controller
    {
        //
        // GET: /Error404/
        public ActionResult Index()
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return View();

            var model = new NotificationsVM();

            model.notifications = DalUnitOfWork.Instance.NotificationsRepository.GetAllProductCreateNotifications();

            return View(model);
        }

        public ActionResult GetProductNotifications()
        {
            return View();
        }

        public string DeleteProductNotification(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            return DalUnitOfWork.Instance.NotificationsRepository.Delete(new Guid(id)) ? "K" : "F";
        }
    }
}

DelightGenie/Views/Notifications/Index.cshtml
@using DelightGenie.Models.DbModels.NotificationModels
@model DelightGenie.Models.ViewModels.AdminVM.NotificationsVM

<div>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>The user who made the request</th>
                <th>Product</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="groupsTable">
            @if (Model != null && Model.notifications != null)
            {
                int i = 0;
                foreach (ProductCreateNotification notification in Model.notifications)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@notification.Employee.UserName</td>
                        <td>@notification.ProductName</td>
                        <td>@notification.NotificationDate.ToString()</td>
                        <td>
                            <span class="btn-group">
                                <button class="btn btn-success" data-toggle="modal" data-target="#dashboardmodal" data-remote="/Products/NewProduct/@notification.Id">
                                    Add product
                                </button>
                                @Ajax.ActionLink("Delete", "DeleteProductNotification/" + notification.Id, "Notifications", new AjaxOptions { OnBegin = "if(stop){e.preventDefault();return false;}stop=true;return ask();", OnSuccess = "deleteNotification(data);setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }, new { @class = "btn btn-danger" })
                            </span>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script>
    var stop = false;

    function deleteNotification(data) {
        if (data == "K") {
            showMessage("alert-success", "Notification deleted!");
            loadpagelink("/Notifications/Index");
        } else {
            showMessage("alert-danger", "The delete failed!");
        }
    }

    function ask() {
        if (!confirm('Are you sure you want to delete the notification?')) {
            event.preventDefault();
            setTimeout(function () { stop = false; }, 10);
            return false;
        }
    }
</script>