DelightGenie/Controllers/TransactionsController.cs
using System;
using System.Web.Mvc;
using DelightGenie.DAL;
using DelightGenie.Models.DbModels.AccountModels;
using DelightGenie.Models.DbModels.HistoryModels;
using DelightGenie.Models.ViewModels.AdminVM;
using DelightGenie.Special;

namespace DelightGenie.Controllers
{
    public class TransactionsController : Controller
    {
        public ActionResult TransactionsTable()
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (!(MySession.Current.UserDetails is Employee))
                return View();

            var model = new TransactionsVM();

            model.Transactions =
                DalUnitOfWork.Instance.TransactionsRepository.GetUncommitedTransactionsForEmployee(
                    (Employee) MySession.Current.UserDetails);

            return PartialView(model);
        }

        public string DeleteTransaction(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (!(MySession.Current.UserDetails is Employee))
                return "F";

            try
            {
                Transaction transaction = DalUnitOfWork.Instance.TransactionsRepository.Get(new Guid(id));
                if (transaction.Employee != MySession.Current.UserDetails)
                    return "F";
                return DalUnitOfWork.Instance.TransactionsRepository.Delete(transaction.Id)
                    ? DalUnitOfWork.Instance.UserAccountsRepository.SubstractPointsForUser(
                        MySession.Current.UserDetails.Id, -transaction.Points).Points + ":" +
                      transaction.Id
                    : "F";
            }
            catch (Exception)
            {
                return "F";
            }
        }

        public string UpdateTransaction(string id, string points)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (!(MySession.Current.UserDetails is Employee))
                return "-1";

            Transaction transaction = DalUnitOfWork.Instance.TransactionsRepository.Get(new Guid(id));

            if (transaction.Employee != MySession.Current.UserDetails)
                return "-1";

            if (Convert.ToInt16(points) < 1) return "-3";

            Employee newEmployee =
                DalUnitOfWork.Instance.UserAccountsRepository.SubstractPointsForUser(
                    MySession.Current.UserDetails.Id, Convert.ToInt16(points) - transaction.Points);

            if (newEmployee != null)
            {
                transaction.Points = Convert.ToInt16(points);
                return DalUnitOfWork.Instance.TransactionsRepository.Update(transaction) != null
                    ? newEmployee.Points.ToString()
                    : "-4";
            }

            return "-2";
        }
    }
}

DelightGenie/Views/Transactions/TransactionsTable.cshtml
@using DelightGenie.Models.DbModels.HistoryModels
@model DelightGenie.Models.ViewModels.AdminVM.TransactionsVM
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h2>Points history</h2>
</div>
<div class="modal-body">

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Product Name</th>
                    <th>Points</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                @if (Model != null && Model.Transactions != null)
                {
                    int i = 0;
                    foreach (Transaction transaction in Model.Transactions)
                    {
                        i++;
                        <tr id="row-@transaction.Id">
                            <td>@i</td>
                            <td>@transaction.Product.ProductName</td>
                            <td><input id="points-@transaction.Id" onkeyup=" changeLink('a-@transaction.Id', this.value) " type="text" value="@transaction.Points" size="5" /></td>
                            <td>
                                <span class="btn-group">

                                    @Ajax.ActionLink("Update", "UpdateTransaction", "Transactions", new { id = transaction.Id, points = transaction.Points }, new AjaxOptions { OnSuccess = "updateTransaction(data)" }, new { @class = "btn btn-success", @id = "a-" + transaction.Id })

                                    @Ajax.ActionLink("Delete", "DeleteTransaction/" + transaction.Id, "Transactions", new AjaxOptions { OnBegin = "return ask()", OnSuccess = "deleteTransaction(data)" }, new { @class = "btn btn-danger" })
                                </span>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

    <script>
        function ask() {
            if (!confirm('Are you sure you want to delete the transaction?')) {
                event.preventDefault();
                return false;
            }
        }

        function deleteTransaction(data) {
            if (data != "F") {
                showMessage("alert-success", "Transaction deleted!");
                changePoints(data.substring(0, data.indexOf(":")));
                $('#row-' + data.substring(data.indexOf(":") + 1)).hide();
            } else {
                showMessage("alert-danger", "The delete failed!");
            }
        }

        function updateTransaction(data) {
            if (data == -1) {
                showMessage('alert-danger', 'You don\'t have permission!');
            } else if (data == -2) {
                showMessage('alert-danger', 'You don\'t have enough points!');
            } else if (data == -3) {
                showMessage('alert-danger', 'You can\'t bid less than 1 point!');
            } else if (data >= 0) {
                changePoints(data);
                showMessage('alert-success', 'Transaction updated!');
            } else {
                showMessage('alert-danger', 'Something went wrong!');
            }
        }

        function changeLink(id, value) {
            var newlink = $('#' + id).attr('href');
            newlink = newlink.substring(0, newlink.indexOf("points")) + "points=" + value;
            $('#' + id).attr('href', newlink);
        }
    </script>
</div>