DelightGenie/Models/DbModels/ProductModels/Category.cs
using System.Collections.ObjectModel;
using System.Web.DynamicData;

namespace DelightGenie.Models.DbModels.ProductModels
{
    [TableName("Categories")]
    public class Category : AbstractModel
    {
        public string CategoryName { get; set; }

        public virtual Collection<Product> Products { get; set; }
    }
}

DelightGenie/Controllers/CategoriesController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using DelightGenie.DAL;
using DelightGenie.Models.DbModels.AccountModels;
using DelightGenie.Models.ViewModels.AdminVM;
using DelightGenie.Special;

namespace DelightGenie.Controllers
{
    public class CategoriesController : Controller
    {
        //
        // GET: /Categories/
        public ActionResult Index()
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return PartialView();

            var model = new CategoriesVM
            {
                Categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll()
            };

            return PartialView(model);
        }

        public ActionResult Categories()
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return PartialView();

            var model = new CategoriesVM
            {
                Categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll()
            };

            return PartialView(model);
        }

        public string DeleteCategory(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            return DalUnitOfWork.Instance.CategoriesRepository.Delete(new Guid(id)) ? "K" : "F";
        }

        [HttpPost]
        public string InsertCategory(string categoryName)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            return DalUnitOfWork.Instance.CategoriesRepository.Insert(categoryName) != null ? "K" : "F";
        }

        [HttpPost]
        public string EditCategory(CategoryVM model)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            var category = DalUnitOfWork.Instance.CategoriesRepository.Get(new Guid(model.Id));
            category.CategoryName = model.Name;

            return DalUnitOfWork.Instance.CategoriesRepository.Update(category) != null ? "K" : "F";
        }

        public ActionResult GetCategory(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Content("<h1>Access denided!</h1>");

            var category = DalUnitOfWork.Instance.CategoriesRepository.Get(new Guid(id));
            var model = new CategoryVM
            {
                Id = category.Id.ToString(),
                Name = category.CategoryName
            };

            return PartialView(model);
        }

        public ActionResult GetCategories()
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return Json(null, JsonRequestBehavior.AllowGet);

            try
            {
                var categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll().Select(p => new
                {
                    p.Id,
                    p.CategoryName
                });

                return Json(categories, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

DelightGenie/Controllers/ProductsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using DelightGenie.DAL;
using DelightGenie.Models.DbModels.AccountModels;
using DelightGenie.Models.DbModels.NotificationModels;
using DelightGenie.Models.DbModels.ProductModels;
using DelightGenie.Models.ViewModels.AdminVM;
using DelightGenie.Special;

namespace DelightGenie.Controllers
{
    public class ProductsController : Controller
    {
        //
        // GET: /Products/
        public ActionResult Index()
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return PartialView();

            var model = new ProductsVM
            {
                Categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll()
            };

            return PartialView(model);
        }

        public ActionResult NewProduct(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Content("<h1>Access denided!</h1>");

            ProductCreateNotification productDetail = null;
            if (id != null)
                productDetail = DalUnitOfWork.Instance.NotificationsRepository.GetProductCreateNotification(new Guid(id));

            try
            {
                var model = new ProductVM();
                if (productDetail != null)
                {
                    model.Name = productDetail.ProductName;
                    model.NotificationId = productDetail.Id.ToString();
                }
                model.Categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll();

                return PartialView(model);
            }
            catch (Exception)
            {
                return Content("<h1>Bad things happened!</h1>");
            }
        }

        public string EditProduct(ProductVM model)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            var productDetails = DalUnitOfWork.Instance.ProductsRepository.Get(new Guid(model.Id));

            if (model.Name == null || model.Name.Length < 2)
                return "N";

            if (model.Price <= 0) return "P";

            productDetails.ProductName = model.Name;
            productDetails.ProductDescription = model.Description;
            productDetails.ProductPrice = model.Price;
            productDetails.Category = DalUnitOfWork.Instance.CategoriesRepository.Get(new Guid(model.Category));

            return DalUnitOfWork.Instance.ProductsRepository.Update(productDetails) != null ? "K" : "F";
        }

        public string CreateProduct(ProductVM model)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            var productDetails = new Product();

            if (model.Name == null || model.Name.Length < 2)
                return "N";

            if (model.Price <= 0) return "P";

            productDetails.ProductName = model.Name;
            productDetails.ProductDescription = model.Description;
            productDetails.ProductPrice = model.Price;
            productDetails.Category = DalUnitOfWork.Instance.CategoriesRepository.Get(new Guid(model.Category));

            if (!string.IsNullOrEmpty(model.NotificationId))
                DalUnitOfWork.Instance.NotificationsRepository.Delete(new Guid(model.NotificationId));

            return DalUnitOfWork.Instance.ProductsRepository.Insert(productDetails) != null ? "K" : "F";
        }

        public ActionResult ProductsTable(string categoryId)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return PartialView();

            try
            {
                if (categoryId == "0")
                {
                    var model = new ProductsVM
                    {
                        Products = DalUnitOfWork.Instance.ProductsRepository.GetAll()
                    };
                    return PartialView(model);
                }
                else
                {
                    var model = new ProductsVM
                    {
                        Products = DalUnitOfWork.Instance.CategoriesRepository.GetProducts(new Guid(categoryId))
                    };
                    return PartialView(model);
                }
            }
            catch (Exception)
            {
                return PartialView();
                ;
            }
        }

        public ActionResult GetProduct(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Content("<h1>Access denided!</h1>");

            try
            {
                var product = DalUnitOfWork.Instance.ProductsRepository.Get(new Guid(id));
                var model = new ProductVM
                {
                    Id = id,
                    Name = product.ProductName,
                    Description = product.ProductDescription,
                    Category = product.Category.Id.ToString(),
                    Price = product.ProductPrice,
                    Categories = DalUnitOfWork.Instance.CategoriesRepository.GetAll()
                };

                return PartialView(model);
            }
            catch (Exception)
            {
                return Content("<h1>Inexistent product!</h1>");
            }
        }

        public string DeleteProduct(string id)
        {
            if (MySession.Current.UserDetails == null)
                MySession.Current.UserDetails = new AccountController().GetUserDetails();

            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            return DalUnitOfWork.Instance.ProductsRepository.Delete(new Guid(id)) ? "K" : "F";
        }

        public ActionResult GetProducts(string categoryId)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return Json(null, JsonRequestBehavior.AllowGet);
            try
            {
                if (categoryId == "0")
                {
                    var products =
                    DalUnitOfWork.Instance.ProductsRepository.GetAll().Select(p => new
                    {
                        p.Id,
                        p.ProductName,
                        p.ProductDescription,
                        p.ProductPrice,
                        p.Category.CategoryName
                    });
                    return Json(products, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var products =
                    DalUnitOfWork.Instance.CategoriesRepository.GetProducts(new Guid(categoryId)).Select(p => new
                    {
                        p.Id,
                        p.ProductName,
                        p.ProductDescription,
                        p.ProductPrice,
                        p.Category.CategoryName
                    });
                    return Json(products, JsonRequestBehavior.AllowGet);
                }
            }
            catch
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public string RequestProduct(string productName)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return "F";

            return DalUnitOfWork.Instance.NotificationsRepository.InsertProductCreateNotification(productName, "",
                MySession.Current.UserDetails as Employee) != null
                ? "K"
                : "F";
        }

        [HttpPost]
        public int Vote(string productId, int points)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return -1;

            if (points < 1) return -2;

            var product = DalUnitOfWork.Instance.ProductsRepository.Get(new Guid(productId));
            var employee = DalUnitOfWork.Instance.UserAccountsRepository.SubstractPointsForUser(
                MySession.Current.UserDetails.Id, points);
            var transaction = DalUnitOfWork.Instance.TransactionsRepository.Insert(points, product,
                MySession.Current.UserDetails as Employee);
            var user = MySession.Current.UserDetails = new AccountController().GetUserDetails();

            return (product != null && employee != null && transaction != null && user != null)
                ? (user as Employee).Points
                : -2;
        }
    }
}

DelightGenie/Views/Categories/GetCategory.cshtml
@model DelightGenie.Models.ViewModels.AdminVM.CategoryVM

<script>
    var stop = false;
</script>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h2>Edit category @Model.Name</h2>
</div> 
<div class="modal-body">

    @using (Ajax.BeginForm("EditCategory", "Categories", new AjaxOptions { OnBegin = "if(stop)e.preventDefault();$('#loading').show();stop=true;", OnSuccess = "editCategory(data);stopForm=false;setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }))
    {
        @Html.HiddenFor(m => m.Id)
        <table class="table">
            <tr>
                <td>@Html.LabelFor(m => m.Name)</td>
                <td>@Html.TextBoxFor(m => m.Name)</td>
            </tr>
        </table>
        <input class="btn btn-success" type="submit" value="Save Category!" />
    }
</div>

DelightGenie/Views/Categories/Index.cshtml
@using DelightGenie.Models.DbModels.ProductModels
@model DelightGenie.Models.ViewModels.AdminVM.CategoriesVM


<style>
    table td { padding-right: 10px; }
</style>

<h1>Product categories</h1>
<div class="myh">
    <form onsubmit=" createCategory() ">
        <table>
            <tr>
                <td>Create a new category </td>
                <td>
                    <input type="text" id="categoryname" class="form-control" placeholder="Insert category name" />
                </td>
                <td>
                    <input type="submit" class="btn btn-success" value="Create category!" />
                </td>
            </tr>
        </table>
    </form>
</div>

<br /><br />



<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Category name</th>
                <th>Number of products</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="categoryTable">
            @if (Model != null && Model.Categories != null)
            {
                int i = 0;
                foreach (Category category in Model.Categories)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@category.CategoryName</td>
                        <td>@(category.Products != null ? category.Products.Count : 0)</td>
                        <td>
                            <span class="btn-group">
                                <button class="btn btn-warning" data-toggle="modal" data-target="#dashboardmodal" data-remote="/Categories/GetCategory/@(category.Id)">
                                    Edit
                                </button>
                                @Ajax.ActionLink("Delete", "DeleteCategory/" + category.Id, "Products", new AjaxOptions { OnBegin = "if(stop){e.preventDefault();return false;}stop=true;return ask();", OnSuccess = "deleteCategory(data);setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);" }, new { @class = "btn btn-danger" })
                            </span>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script>
    var stop = false;

    function deleteCategory(data) {
        if (data == "K") {
            showMessage("alert-success", "Category deleted!");
            loadpagelink("/Categories/Index");
        } else {
            showMessage("alert-danger", "The delete failed!");
        }
    }

    function createCategory() {
        event.preventDefault();
        var categoryName = $('#categoryname').val();

        if (categoryName.length < 3) {
            showMessage('alert-danger', 'Insert at least 3 characters!');
            return;
        }

        $("#loading").show();

        $.ajax({
            type: "POST",
            url: "/Categories/InsertCategory",
            data: { categoryName: categoryName },
            context: this,
            success: function(data) {
                showMessage("alert-success", "Category added!");
                loadpagelink("/Categories/Index");
            },
            error: function(data) {
                showMessage('alert-danger', 'Adding the category failed!');
                $("#loading").hide();
            }
        });
        return false;
    }

    function editCategory(data) {
        if (data == "K") {
            showMessage("alert-success", "Category modified!");
            loadpagelink("/Categories/Index");
            $('.modal').modal('hide');
            $('body').removeClass('modal-open');
            $('.modal-backdrop').remove();
        } else if (data == "N") {
            showMessage('alert-danger', 'Insert at least 3 characters!');
        }
        else {
            showMessage("alert-danger", "The modification failed!");
        }
    }

    function ask() {
        if (!confirm('Are you sure you want to delete the category?')) {
            event.preventDefault();
            setTimeout(function () { stop = false; }, 10);
            return false;
        }
    }
</script>