DelightGenie/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web.Mvc;
using DelightGenie.DAL;
using DelightGenie.Models.DbModels.AccountModels;
using DelightGenie.Models.DbModels.HistoryModels;
using DelightGenie.Models.ViewModels;
using DelightGenie.Models.ViewModels.AdminVM;
using DelightGenie.Special;

namespace DelightGenie.Controllers
{
    public class PurchasesController : Controller
    {
        //
        // GET: /Purchases/


        public ActionResult Index()
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return Redirect("/Home/Index");
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Redirect("/Home/Index/#notadmin");

            var model = new CommitsVM
            {
                Commits =
                    DalUnitOfWork.Instance.CommitsRepository.GetAll().OrderByDescending(p => p.CommitDate).ToArray()
            };

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult GetCommitTable(string id)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return Redirect("/Home/Index");
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Redirect("/Home/Index/#notadmin");

            Commit commit = DalUnitOfWork.Instance.CommitsRepository.Get(new Guid(id));
            if (commit == null) return PartialView();

            var model = new PurchasesVM();
            var results = new List<ResultModel>();
            foreach (Purchase purchase in commit.Purchases)
            {
                results.Add(new ResultModel
                {
                    NrItems = purchase.NumberOfItems,
                    AllPrice = purchase.ItemPrice*purchase.NumberOfItems,
                    ProductId = purchase.Product.Id.ToString(),
                    ProductName = purchase.Product.ProductName,
                    ProductPrice = purchase.ItemPrice,
                    TotalScore = purchase.Points
                });

                model.TotalAllPrice += purchase.ItemPrice*purchase.NumberOfItems;
            }

            model.Results = results.OrderByDescending(p => p.TotalScore).ToArray();
            model.ViewExistent = true;
            model.CommitID = commit.Id.ToString();

            return PartialView("GenerateReport", model);
        }

        /// <summary>
        ///     Generate the report for the uncommited point allocations
        /// </summary>
        /// <param name="budget">The budget for this month</param>
        /// <param name="submitcommit">Whether the report should be saved as accepted 0/1</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GenerateReport(float budget, int submitcommit)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return Redirect("/Home/Index");
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return Redirect("/Home/Index/#notadmin");

            try
            {
                Transaction[] transactions =
                    DalUnitOfWork.Instance.TransactionsRepository.GetTransactionsForCommit(null);
                var results = new List<ResultModel>();

                var model = new PurchasesVM { TotalAllScore = 0, TotalAllPrice = 0 };

                float fakeTotalPrice = 0;

                foreach (Transaction transaction in transactions)
                {
                    int sum = transaction.Points;
                    model.TotalAllScore += sum;
                    fakeTotalPrice += sum*transaction.Product.ProductPrice;

                    results.Add(new ResultModel
                    {
                        ProductId = transaction.Product.Id.ToString(),
                        ProductName = transaction.Product.ProductName,
                        ProductPrice = transaction.Product.ProductPrice,
                        TotalScore = sum
                    });
                }

                Commit commit = null;
                if (submitcommit == 1)
                {
                    DalUnitOfWork.Instance.CommitsRepository.Insert(budget);
                    commit = DalUnitOfWork.Instance.CommitsRepository.GetLastCommit();
                    commit.Purchases = new Collection<Purchase>();
                }

                float alpha = budget/fakeTotalPrice;
                for (int i = 0; i < results.Count; i++)
                {
                    //results[i].Percentage = (float)results[i].TotalScore / model.TotalAllScore * 100;
                    //results[i].NrItems = (int)(((results[i].Percentage / 100 * budget) / results[i].ProductPrice));

                    //Now calculate the percent from number of products

                    results[i].NrItems = (int)(alpha * results[i].TotalScore);
                    results[i].AllPrice = results[i].NrItems * results[i].ProductPrice;
                    model.TotalAllPrice += results[i].AllPrice;

                    if (commit != null && submitcommit == 1 && results[i].NrItems > 0)
                    {
                        commit.Purchases.Add(new Purchase
                        {
                            Id = Guid.NewGuid(),
                            Product = DalUnitOfWork.Instance.ProductsRepository.Get(new Guid(results[i].ProductId)),
                            ItemPrice = results[i].ProductPrice,
                            NumberOfItems = results[i].NrItems,
                            Commit = commit,
                            Points = results[i].TotalScore
                        });
                    }
                }

                if (submitcommit == 1)
                {
                    DalUnitOfWork.Instance.CommitsRepository.Update(commit);
                    foreach (var group in DalUnitOfWork.Instance.GroupsRepository.GetAll())
                    {
                        DalUnitOfWork.Instance.GroupsRepository.ResetGroupPoints(group.Id);
                    }
                }

                model.Results = results.Where(p => p.NrItems != 0).OrderByDescending(p => p.TotalScore).ToArray();

                return PartialView(model);
            }
            catch
            {
                return PartialView();
            }
        }

        public string DeleteCommit(string id)
        {
            if (MySession.Current.UserDetails == null ||
                (MySession.Current.UserDetails = new AccountController().GetUserDetails()) == null)
                return "F";
            if (MySession.Current.UserDetails == null || MySession.Current.UserDetails is Employee)
                return "F";

            if (id == null || DalUnitOfWork.Instance.CommitsRepository.Delete(new Guid(id)) == false) return "F";

            try
            {
                foreach (var employee in DalUnitOfWork.Instance.UserAccountsRepository.GetAllEmployees())
                {
                    var points = DalUnitOfWork.Instance.TransactionsRepository.GetUncommitedTransactionsForEmployee(employee).Sum(t => t.Points);
                    employee.Points = employee.Group.Points - points;
                    DalUnitOfWork.Instance.UserAccountsRepository.Update(employee);
                }
                return "K";
            }
            catch
            {
                return "F";
            }
        }
    }
}

DelightGenie/Views/Purchases/GenerateReport.cshtml
@using DelightGenie.Models.ViewModels
@model DelightGenie.Models.ViewModels.AdminVM.PurchasesVM
<script>
    var stop = false;
</script>

<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <!--th>Score Percentage</th-->
                <th>Total Score</th>
                <th>Nr. Items</th>
                <th>Product budget</th>
            </tr>
        </thead>
        <tbody id="groupsTable">
            @if (Model != null && Model.Results != null)
            {
                int i = 0;
                foreach (ResultModel r in Model.Results)
                {
                    i++;
                    <tr>
                        <td>@i</td>
                        <td>@r.ProductName</td>
                        <td>@r.ProductPrice</td>
                        <!--td>@r.Percentage</td-->
                        <td>@r.TotalScore</td>
                        <td>@r.NrItems</td>
                        <td>@r.AllPrice</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<br />

@if (Model.ViewExistent == false)
{
    <h3>The total price is @(Model != null ? Model.TotalAllPrice : 0)</h3>
    <input type="button" class="btn btn-success" onclick=" createCommit(1) " value="Submit the report !" />
}
else
{
    <h3>The total price is @(Model != null ? Model.TotalAllPrice : 0)</h3>
    <a href="/Reports/GetReportXls/@Model.CommitID" class="btn btn-success">Download as xls !</a>
    <a href="/Reports/GetReportPdf/@Model.CommitID" class="btn btn-success">Download as pdf !</a>
    @Ajax.ActionLink("Delete commit!", "DeleteCommit/" + Model.CommitID, "Purchases", new AjaxOptions {OnBegin = "if(stop)e.preventDefault();stop=true;return ask()", OnSuccess = "deleteCommit(data);stopForm=false;setTimeout(function () { stop = false; }, 10);", OnFailure = "showMessage('alert-danger', 'Failed!');setTimeout(function () { stop = false; }, 10);"}, new {@class = "btn btn-danger"})
}

DelightGenie/Views/Purchases/Index.cshtml
@using DelightGenie.Models.DbModels.HistoryModels
@model DelightGenie.Models.ViewModels.AdminVM.CommitsVM

<style>
    table td { padding-right: 10px; }
</style>
<script>
    var c = 0;
</script>

<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#endmonth" role="tab" data-toggle="tab">Create a new shopping list</a></li>
    <li><a href="#viewcommits" role="tab" data-toggle="tab">View earlier purchases</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    <div class="tab-pane active" id="endmonth">
        <h1>Make the final 'shopping list'</h1>
        <div class="myh">
            <form onsubmit=" createCommit(0) ">
                <table>
                    <tr>
                        <td>Enter your budget</td>
                        <td>
                            <input type="text" id="budget" class="form-control" placeholder="Insert budget" />
                        </td>
                        <td>
                            <input type="submit" class="btn btn-success" onclick=" createCommit(0) " value="Preview the report !" />
                        </td>
                        <td></td>
                    </tr>
                </table>
            </form>
        </div>

        <br /><br />

        <div id="generation">

        </div>
    </div>

    <div class="tab-pane" id="viewcommits">
        <br/>
        <div class="myh">
            <table>
                <tr>
                    <td>Select the commit </td>
                    <td>
                        <select id="commitslist" class="form-control" onchange=" loadCommit(this.value) ">
                            <option value="0"></option>
                            @if (Model != null && Model.Commits != null)
                            {
                                foreach (Commit commit in Model.Commits)
                                {
                                    <option value="@commit.Id">@commit.CommitDate</option>
                                }
                            }
                        </select>
                    </td>
                </tr>
            </table>
        </div>
        <br />
        <div id="committable"></div>
    </div>
</div>



<script>
    function createCommit(commit) {
        event.preventDefault();
        $("#loading").show();

        var budget = $("#budget").val();
        $.ajax({
            type: "POST",
            url: "/Purchases/GenerateReport",
            data: { budget: budget, submitcommit: commit },
            context: this,
            success: function(data) {
                $("#loading").hide();
                showMessage("alert-success", "Done!");
                if (commit) loadpagelink("/Purchases/Index");
                else
                    $("#generation").html(data);
            },
            error: function(data) {
                showMessage('alert-danger', 'Failed!');
                $("#loading").hide();
            }
        });
        return false;
    }

    function loadCommit(commitId) {
        if (commitId == 0) return;

        $("#loading").show();

        $.ajax({
            type: "POST",
            url: "/Purchases/GetCommitTable",
            data: { id: commitId },
            context: this,
            success: function(data) {
                $("#committable").html(data);
                $("#loading").hide();
            },
            error: function(data) {
                showMessage('alert-danger', 'The selected commit cannot be fetched from the server!');
                $("#loading").hide();
            }
        });
    }

    function deleteCommit(data) {
        if (data == "K") {
            showMessage("alert-success", "Commit deleted!");
            loadpagelink("/Purchases/Index");
        } else {
            showMessage("alert-danger", "The delete failed!");
        }
    }

    function ask() {
        if (!confirm('Are you sure you want to delete the commit?')) {
            event.preventDefault();
            return false;
        }
    }

</script>